### ISSUE TITLE
Doesn't work if always_mitm is false and regex: true

### ISSUE THREAD

**Issue by kajikentaro** [kajikentaro/flexy-proxy#7]
**reproduce**

command:

`flexy-proxy -f config.yaml`

confg.yaml:
```
always_mitm: false

routes:
  - url: "https://example.com/.*"
    regex: true
    response:
```

output: 
```
validation error: Regular expressions are not allowed in the hostname when `always_mitm` is disabled. Found: "example.com" on route.0
```
